//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaWeb.ServiceCalculadora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCalculadora.WebServiceCalculadoraSoap")]
    public interface WebServiceCalculadoraSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soma", ReplyAction="*")]
        int Soma(int numero1, int numero2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCalculadoraSoapChannel : BibliotecaWeb.ServiceCalculadora.WebServiceCalculadoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCalculadoraSoapClient : System.ServiceModel.ClientBase<BibliotecaWeb.ServiceCalculadora.WebServiceCalculadoraSoap>, BibliotecaWeb.ServiceCalculadora.WebServiceCalculadoraSoap {
        
        public WebServiceCalculadoraSoapClient() {
        }
        
        public WebServiceCalculadoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCalculadoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculadoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCalculadoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Soma(int numero1, int numero2) {
            return base.Channel.Soma(numero1, numero2);
        }
    }
}
